### ISSUE TITLE
Hang while installing Netrunner Rolling

### ISSUE THREAD

**Issue by aleixpol** [netrunner-rolling/calamares-netrunner-rolling#1]
I was using it on VirtualBox, it would hang every time.
I solved the issue by increasing the RAM allocated to 2GiB.
Initially I was using 1GiB (although the default was 512 MiB).

**Comment by NuLogicSystems** [comment]
Yes, for some reason Plasma 5 is requiring 2 gigs of ram to function with
the compositor on and set to opengl.
I'm not sure if this is the new Intel dri, xorg, mesa drivers or the new
compositor that is causing the issue.

**Comment by aleixpol** [comment]
I insist that it's on virtualbox, so it's certainly not intel's fault.
I don't see a big usage of memory on the plasma+kwin side (although it will be quite lower on 5.4 because of the shared engines). Anyway, I'd suggest to investigate within Calamares, since Plasma works well until the installation starts.

**Comment by NuLogicSystems** [comment]
Oh, I misunderstood. It's only calamares that's freezing.
Please report this to Teo and on the calamares github.
https://github.com/calamares/calamares

This github only contains Netrunner rolling branding calamares and a few
needed modules from Manjaro.
It's basically a modified port of the Manjaro github for branding.
https://github.com/calamares/calamares

**Comment by aleixpol** [comment]
I don't think it's up to me to report it upstream.

@teo ping

**Comment by NuLogicSystems** [comment]
Teo, can you look into this if it isn't already fixed and in the upcoming
calamares 1.1.2.
https://github.com/netrunner-rolling/calamares-netrunner-rolling/issues/1

**Comment by teo** [comment]
@aleixpol what happens exactly, does RAM usage spike at some point? How much?

**Comment by NuLogicSystems** [comment]
@aleixpol
Also which Netrunner Rolling ISO are you using?

**Comment by aleixpol** [comment]
@AJSlye I used: netrunner-rolling-2015.06.rc1-x86_64.iso

@teo it basically froze, if I resized the virtualbox machine it would turn black. It still had disk IO, although I tried to leave it running and see if it finished and it wouldn't. I guess it was swapping like crazy.

**Comment by NuLogicSystems** [comment]
@aleixpol
Please try upgrading Calamares from the Netrunner repository while booted into the live enviroment, it has been updated since then for the pre2 ISO.
Or try using the pre2 ISO instead, just do not announce this ISO publicly. 
http://arch.netrunner-os.com/ISO/netrunner-rolling-2015.06-pre2-x86_64.iso
http://arch.netrunner-os.com/ISO/netrunner-rolling-2015.06-pre2-x86_64.iso.md5

**Comment by teo** [comment]
@aleixpol so everything felt fine until it got to the install phase?
@AJSlye I don't think upgrading would help here, I haven't made any changes that would impact memory management that much.

**Comment by NuLogicSystems** [comment]
@Teo
Yes, but could it be one of the Manjaro modules causing the issue.

@aleixpol
Try stoping zramswap prior to running Calamares.
sudo systemctl stop zramswap

**Comment by aleixpol** [comment]
@teo yes, everything was fine, as fine as it gets with a livecd on a virtualbox.

**Comment by teo** [comment]
@aleixpol ok, thanks, I'll investigate.
@AJSlye since you mentioned Manjaro modules, have you made any changes to the unpackfs module?

**Comment by NuLogicSystems** [comment]
@Teo,
I didn't but Manjaro may have.

Could this also be caused by the size of the graphics used for the slide
show?

**Comment by aleixpol** [comment]
It definitely can, especially if it's being scaled down and the original is kept in memory.

**Comment by NuLogicSystems** [comment]
Should I re-size the actual images down then or ask for smaller versions?

**Comment by teo** [comment]
@AJSlye nope, those 8 pictures, with scaling and whatnot, are a few MB in memory, tops. Something else is going on.
