### ISSUE TITLE
wired network connection on my test box (Realtek 8111/8168/8411) is dropped

### ISSUE THREAD

**Issue by hphilm** [netrunner-rolling/calamares-netrunner-rolling#2]
I got an e-mail by Teo:

> Hi Philip,
> 
> I've noticed that during the mhwd run while installing Netrunner with 
> Calamares, when mhwd apparently sets up network drivers, the wired network 
> connection on my test box (Realtek 8111/8168/8411) is dropped and the device 
> node gets destroyed (and ip addr doesn't show it any more). After that I can't 
> connect to wired ethernet until I reboot. This is all happening in the live 
> session.
> 
> https://paste.kde.org/pbfk5oiw7
> 
> I'm reporting this to you since I assume the issue might be present on Manjaro 
> as well, and you're our upstream for mhwd. Is this a known issue? Please let 
> me know if there's any other info I can provide.
> 
> Cheers,
> -- Teo Mrnjavac http://teom.org | teo@kde.org

This is fixed [upstream](https://github.com/calamares/calamares-manjaro/commit/12a5fef5bb029249c94adbe198e64ccd6146ccea).

**Comment by NuLogicSystems** [comment]
I'll fix this here as well and upload a new Calamares 1.1.4.2-7 to our Netrunner repository.
Thanks for the heads up.

**Comment by hphilm** [comment]
Fixed with 2021cba04cd169cc41f0512868761d489c65663c
